services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://share_it_ats_user:10x5C.0_0T0N7@35.226.215.172:5432/share_it_ats

    volumes:
      - .:/app
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_HOST: "35.226.215.172"
      POSTGRES_USER: share_it_ats_user
      POSTGRES_PASSWORD: 10x5C.0_0T0N7
      POSTGRES_DB: share_it_ats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
